// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class AdministeredPayment_processPayment : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"AdministeredPayment_processPayment\",\"namespace\":\"cz.csas" +
				".avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"chann" +
				"el\",\"type\":\"string\"},{\"name\":\"externalLiabilityIds\",\"default\":null,\"type\":[\"null" +
				"\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ExternalLiability\",\"namespace" +
				"\":\"cz.csas.avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"na" +
				"me\":\"externalLiabilityId\",\"doc\":\"Externi id zavazku\",\"type\":\"string\"}]}}]},{\"nam" +
				"e\":\"isin\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"orgUnitId\",\"doc\":\"id" +
				"entifikator pobocky (organizacni jednotky), napr. \\\"001222_001_PRAHA 1,PC_PRAHA " +
				"1 (RYTIRSKA)\\\", \\\"CE7530_01_TYM VYVOJ A PODPORA INTERNICH APLIKACI\\\", ...\",\"defa" +
				"ult\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"paymentInstruction\",\"type\":{\"type\":" +
				"\"record\",\"name\":\"PaymentInstruction\",\"namespace\":\"cz.csas.avroschemas.administer" +
				"edpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"domesticAccount\",\"default\":n" +
				"ull,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DomesticAccount\",\"namespace\":\"cz.csa" +
				"s.avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"acco" +
				"untNumber\",\"doc\":\"Bank Account Number\",\"type\":\"string\"},{\"name\":\"accountPrefix\"," +
				"\"doc\":\"Bank Account Number Prefix\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"bankCode\",\"doc\":\"Bank Code\",\"type\":\"string\"}]}]},{\"name\":\"foreignAccount\",\"" +
				"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ForeignAccount\",\"namespace" +
				"\":\"cz.csas.avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"na" +
				"me\":\"accountName\",\"doc\":\"Nazev uctu (dlouha varianta) v primarnim systemu (SB, S" +
				"PZ, ...). Muze mit delku az 60 znaku.\",\"default\":null,\"type\":[\"null\",\"string\"]}," +
				"{\"name\":\"bic\",\"type\":\"string\"},{\"name\":\"iban\",\"type\":\"string\"},{\"name\":\"notice\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]}]}]}]}},{\"name\":\"paymentReceiver\",\"type\"" +
				":{\"type\":\"record\",\"name\":\"PaymentReceiver\",\"namespace\":\"cz.csas.avroschemas.admi" +
				"nisteredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"idCard\",\"default\":null" +
				",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"IdCard\",\"namespace\":\"cz.csas.avroschema" +
				"s.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"cardNumber\",\"doc" +
				"\":\"cislo dokladu\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"cardType\",\"d" +
				"oc\":\"typ ID dokladu (OP, cestovni pas, ridicsky prukaz...)\",\"default\":null,\"type" +
				"\":[\"null\",\"string\"]},{\"name\":\"issuer\",\"doc\":\"Udava kdo doklad vydal (urad).\",\"de" +
				"fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"issuerCountry\",\"doc\":\"(doklad) vy" +
				"dal stat\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"validUntil\",\"default" +
				"\":null,\"type\":[\"null\",{\"type\":\"int\",\"logicalType\":\"date\"}]}]}]},{\"name\":\"liabili" +
				"tyPaymentRoleType\",\"type\":\"string\"},{\"name\":\"permanentAddress\",\"default\":null,\"t" +
				"ype\":[\"null\",{\"type\":\"record\",\"name\":\"PermanentAddress\",\"namespace\":\"cz.csas.avr" +
				"oschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"l1_recipi" +
				"ent\",\"doc\":\"Adresni radek 1 Prijmeni, Jmeno, Titul pred, Titul za\\r\\n\\r\\nPouziti" +
				" formatovane adresy je popsano primo v entite PostalAddress.\",\"default\":null,\"ty" +
				"pe\":[\"null\",\"string\"]},{\"name\":\"l2_supplement\",\"doc\":\"Adresni radek 2, Doplnek\\r" +
				"\\n\\r\\nPouziti formatovane adresy je popsano primo v entite PostalAddress.\",\"defa" +
				"ult\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"l3_street\",\"doc\":\"Adresni radek 3, " +
				"Ulice (nebo Cast obce, kdyz je pole Ulice prazdne), „Cislo popisne/orientacni“ n" +
				"ebo „Cislo evidencni\\r\\n\\r\\nPouziti formatovane adresy je popsano primo v entite" +
				" PostalAddress.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"l4_city\",\"doc" +
				"\":\"Adresni radek 4, Obec/Cast Obce\\r\\n\\r\\nPouziti formatovane adresy je popsano " +
				"primo v entite PostalAddress.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"l5_zipcode\",\"doc\":\"Adresni radek 5, PSC, Posta\\r\\n\\r\\nPouziti formatovane adres" +
				"y je popsano primo v entite PostalAddress.\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"l6_country\",\"doc\":\"Adresni radek 6, Stat. Pokud je to CR, pole se " +
				"nevraci.\\r\\n\\r\\nPouziti formatovane adresy je popsano primo v entite PostalAddre" +
				"ss.\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"person\",\"type\":{\"type" +
				"\":\"record\",\"name\":\"Person\",\"namespace\":\"cz.csas.avroschemas.administeredpayment_" +
				"processpayment.v03_01\",\"fields\":[{\"name\":\"additionalDegree\",\"doc\":\"Additional ac" +
				"ademic degree. (Titul za jmenem.)\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"birthCountry\",\"doc\":\"zeme narozeni\",\"default\":null,\"type\":[\"null\",\"string\"]" +
				"},{\"name\":\"birthPlace\",\"doc\":\"misto (mesto) narozeni\",\"default\":null,\"type\":[\"nu" +
				"ll\",\"string\"]},{\"name\":\"citizenships\",\"default\":null,\"type\":[\"null\",{\"type\":\"arr" +
				"ay\",\"items\":{\"type\":\"record\",\"name\":\"Citizenship\",\"namespace\":\"cz.csas.avroschem" +
				"as.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"citizenship\",\"d" +
				"oc\":\"statni prislusnost / obcanstvi\",\"type\":\"string\"}]}}]},{\"name\":\"degree\",\"doc" +
				"\":\"Academic degree. (titul pred)\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"nam" +
				"e\":\"email\",\"doc\":\"emailova adresa\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"forename\",\"doc\":\"(krestni) jmeno\",\"type\":\"string\"},{\"name\":\"gender\",\"doc\":\"" +
				"pohlavi\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"personalId\",\"doc\":\"Pr" +
				"o ceske obcany to je rodne cislo. Pro cizince cislo odvozene od datumu narozani " +
				"(jak rc) a posledne 4 cislice jsou devitky. Proto cizinci narozeni v jednom dni " +
				"je maji rovnake.\",\"type\":\"string\"},{\"name\":\"surname\",\"doc\":\"prijmeni\",\"type\":\"st" +
				"ring\"},{\"name\":\"taxResidency\",\"default\":null,\"type\":[\"null\",\"string\"]}]}},{\"name" +
				"\":\"verified\",\"type\":\"boolean\"}]}},{\"name\":\"requestDate\",\"type\":{\"type\":\"long\",\"l" +
				"ogicalType\":\"timestamp-millis\"}},{\"name\":\"requestId\",\"default\":null,\"type\":[\"nul" +
				"l\",\"string\"]},{\"name\":\"token\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"" +
				"userName\",\"default\":null,\"type\":[\"null\",\"string\"]}]}");
		private string _channel;
		private IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ExternalLiability> _externalLiabilityIds;
		private string _isin;
		/// <summary>
		/// identifikator pobocky (organizacni jednotky), napr. "001222_001_PRAHA 1,PC_PRAHA 1 (RYTIRSKA)", "CE7530_01_TYM VYVOJ A PODPORA INTERNICH APLIKACI", ...
		/// </summary>
		private string _orgUnitId;
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentInstruction _paymentInstruction;
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentReceiver _paymentReceiver;
		private System.DateTime _requestDate;
		private string _requestId;
		private string _token;
		private string _userName;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AdministeredPayment_processPayment._SCHEMA;
			}
		}
		public string channel
		{
			get
			{
				return this._channel;
			}
			set
			{
				this._channel = value;
			}
		}
		public IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ExternalLiability> externalLiabilityIds
		{
			get
			{
				return this._externalLiabilityIds;
			}
			set
			{
				this._externalLiabilityIds = value;
			}
		}
		public string isin
		{
			get
			{
				return this._isin;
			}
			set
			{
				this._isin = value;
			}
		}
		/// <summary>
		/// identifikator pobocky (organizacni jednotky), napr. "001222_001_PRAHA 1,PC_PRAHA 1 (RYTIRSKA)", "CE7530_01_TYM VYVOJ A PODPORA INTERNICH APLIKACI", ...
		/// </summary>
		public string orgUnitId
		{
			get
			{
				return this._orgUnitId;
			}
			set
			{
				this._orgUnitId = value;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentInstruction paymentInstruction
		{
			get
			{
				return this._paymentInstruction;
			}
			set
			{
				this._paymentInstruction = value;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentReceiver paymentReceiver
		{
			get
			{
				return this._paymentReceiver;
			}
			set
			{
				this._paymentReceiver = value;
			}
		}
		public System.DateTime requestDate
		{
			get
			{
				return this._requestDate;
			}
			set
			{
				this._requestDate = value;
			}
		}
		public string requestId
		{
			get
			{
				return this._requestId;
			}
			set
			{
				this._requestId = value;
			}
		}
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				this._token = value;
			}
		}
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.channel;
			case 1: return this.externalLiabilityIds;
			case 2: return this.isin;
			case 3: return this.orgUnitId;
			case 4: return this.paymentInstruction;
			case 5: return this.paymentReceiver;
			case 6: return this.requestDate;
			case 7: return this.requestId;
			case 8: return this.token;
			case 9: return this.userName;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.channel = (System.String)fieldValue; break;
			case 1: this.externalLiabilityIds = (IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ExternalLiability>)fieldValue; break;
			case 2: this.isin = (System.String)fieldValue; break;
			case 3: this.orgUnitId = (System.String)fieldValue; break;
			case 4: this.paymentInstruction = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentInstruction)fieldValue; break;
			case 5: this.paymentReceiver = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentReceiver)fieldValue; break;
			case 6: this.requestDate = (System.DateTime)fieldValue; break;
			case 7: this.requestId = (System.String)fieldValue; break;
			case 8: this.token = (System.String)fieldValue; break;
			case 9: this.userName = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
