// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class PaymentReceiver : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"PaymentReceiver\",\"namespace\":\"cz.csas.avroschemas.admini" +
				"steredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"idCard\",\"default\":null,\"" +
				"type\":[\"null\",{\"type\":\"record\",\"name\":\"IdCard\",\"namespace\":\"cz.csas.avroschemas." +
				"administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"cardNumber\",\"doc\":" +
				"\"cislo dokladu\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"cardType\",\"doc" +
				"\":\"typ ID dokladu (OP, cestovni pas, ridicsky prukaz...)\",\"default\":null,\"type\":" +
				"[\"null\",\"string\"]},{\"name\":\"issuer\",\"doc\":\"Udava kdo doklad vydal (urad).\",\"defa" +
				"ult\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"issuerCountry\",\"doc\":\"(doklad) vyda" +
				"l stat\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"validUntil\",\"default\":" +
				"null,\"type\":[\"null\",\"int\"]}]}]},{\"name\":\"liabilityPaymentRoleType\",\"type\":\"strin" +
				"g\"},{\"name\":\"permanentAddress\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"n" +
				"ame\":\"PermanentAddress\",\"namespace\":\"cz.csas.avroschemas.administeredpayment_pro" +
				"cesspayment.v03_01\",\"fields\":[{\"name\":\"l1_recipient\",\"doc\":\"Adresni radek 1 Prij" +
				"meni, Jmeno, Titul pred, Titul za\\r\\n\\r\\nPouziti formatovane adresy je popsano p" +
				"rimo v entite PostalAddress.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"" +
				"l2_supplement\",\"doc\":\"Adresni radek 2, Doplnek\\r\\n\\r\\nPouziti formatovane adresy" +
				" je popsano primo v entite PostalAddress.\",\"default\":null,\"type\":[\"null\",\"string" +
				"\"]},{\"name\":\"l3_street\",\"doc\":\"Adresni radek 3, Ulice (nebo Cast obce, kdyz je p" +
				"ole Ulice prazdne), „Cislo popisne/orientacni“ nebo „Cislo evidencni\\r\\n\\r\\nPouz" +
				"iti formatovane adresy je popsano primo v entite PostalAddress.\",\"default\":null," +
				"\"type\":[\"null\",\"string\"]},{\"name\":\"l4_city\",\"doc\":\"Adresni radek 4, Obec/Cast Ob" +
				"ce\\r\\n\\r\\nPouziti formatovane adresy je popsano primo v entite PostalAddress.\",\"" +
				"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"l5_zipcode\",\"doc\":\"Adresni rade" +
				"k 5, PSC, Posta\\r\\n\\r\\nPouziti formatovane adresy je popsano primo v entite Post" +
				"alAddress.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"l6_country\",\"doc\":" +
				"\"Adresni radek 6, Stat. Pokud je to CR, pole se nevraci.\\r\\n\\r\\nPouziti formatov" +
				"ane adresy je popsano primo v entite PostalAddress.\",\"default\":null,\"type\":[\"nul" +
				"l\",\"string\"]}]}]},{\"name\":\"person\",\"type\":{\"type\":\"record\",\"name\":\"Person\",\"name" +
				"space\":\"cz.csas.avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":" +
				"[{\"name\":\"additionalDegree\",\"doc\":\"Additional academic degree. (Titul za jmenem." +
				")\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"birthCountry\",\"doc\":\"zeme n" +
				"arozeni\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"birthPlace\",\"doc\":\"mi" +
				"sto (mesto) narozeni\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"citizens" +
				"hips\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"na" +
				"me\":\"Citizenship\",\"namespace\":\"cz.csas.avroschemas.administeredpayment_processpa" +
				"yment.v03_01\",\"fields\":[{\"name\":\"citizenship\",\"doc\":\"statni prislusnost / obcans" +
				"tvi\",\"type\":\"string\"}]}}]},{\"name\":\"degree\",\"doc\":\"Academic degree. (titul pred)" +
				"\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"email\",\"doc\":\"emailova adres" +
				"a\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"forename\",\"doc\":\"(krestni) " +
				"jmeno\",\"type\":\"string\"},{\"name\":\"gender\",\"doc\":\"pohlavi\",\"default\":null,\"type\":[" +
				"\"null\",\"string\"]},{\"name\":\"personalId\",\"doc\":\"Pro ceske obcany to je rodne cislo" +
				". Pro cizince cislo odvozene od datumu narozani (jak rc) a posledne 4 cislice js" +
				"ou devitky. Proto cizinci narozeni v jednom dni je maji rovnake.\",\"type\":\"string" +
				"\"},{\"name\":\"surname\",\"doc\":\"prijmeni\",\"type\":\"string\"},{\"name\":\"taxResidency\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]}]}},{\"name\":\"verified\",\"type\":\"boolean\"}]}" +
				"");
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.IdCard _idCard;
		private string _liabilityPaymentRoleType;
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PermanentAddress _permanentAddress;
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.Person _person;
		private bool _verified;
		public virtual Schema Schema
		{
			get
			{
				return PaymentReceiver._SCHEMA;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.IdCard idCard
		{
			get
			{
				return this._idCard;
			}
			set
			{
				this._idCard = value;
			}
		}
		public string liabilityPaymentRoleType
		{
			get
			{
				return this._liabilityPaymentRoleType;
			}
			set
			{
				this._liabilityPaymentRoleType = value;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PermanentAddress permanentAddress
		{
			get
			{
				return this._permanentAddress;
			}
			set
			{
				this._permanentAddress = value;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.Person person
		{
			get
			{
				return this._person;
			}
			set
			{
				this._person = value;
			}
		}
		public bool verified
		{
			get
			{
				return this._verified;
			}
			set
			{
				this._verified = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.idCard;
			case 1: return this.liabilityPaymentRoleType;
			case 2: return this.permanentAddress;
			case 3: return this.person;
			case 4: return this.verified;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.idCard = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.IdCard)fieldValue; break;
			case 1: this.liabilityPaymentRoleType = (System.String)fieldValue; break;
			case 2: this.permanentAddress = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PermanentAddress)fieldValue; break;
			case 3: this.person = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.Person)fieldValue; break;
			case 4: this.verified = (System.Boolean)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
