// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class AdministeredPayment_processPayment : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"AdministeredPayment_processPayment\",\"namespace\":\"cz.csas" +
				".avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"chann" +
				"el\",\"type\":\"string\"},{\"name\":\"externalLiabilityIds\",\"type\":{\"type\":\"array\",\"item" +
				"s\":{\"type\":\"record\",\"name\":\"ExternalLiability\",\"namespace\":\"cz.csas.avroschemas." +
				"administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"externalLiabilityI" +
				"d\",\"doc\":\"Externi id zavazku\",\"type\":\"string\"}]}}},{\"name\":\"orgUnitId\",\"doc\":\"id" +
				"entifikator pobocky (organizacni jednotky), napr. \\\"001222_001_PRAHA 1,PC_PRAHA " +
				"1 (RYTIRSKA)\\\", \\\"CE7530_01_TYM VYVOJ A PODPORA INTERNICH APLIKACI\\\", ...\",\"defa" +
				"ult\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"paymentInstruction\",\"type\":{\"type\":" +
				"\"record\",\"name\":\"PaymentInstruction\",\"namespace\":\"cz.csas.avroschemas.administer" +
				"edpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"domesticAccount\",\"default\":n" +
				"ull,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"DomesticAccount\",\"namespace\":\"cz.csa" +
				"s.avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"acco" +
				"untNumber\",\"doc\":\"Bank Account Number\",\"type\":\"string\"},{\"name\":\"accountPrefix\"," +
				"\"doc\":\"Bank Account Number Prefix\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"na" +
				"me\":\"bankCode\",\"doc\":\"Bank Code\",\"type\":\"string\"}]}]},{\"name\":\"foreignAccount\",\"" +
				"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ForeignAccount\",\"namespace" +
				"\":\"cz.csas.avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"na" +
				"me\":\"accountName\",\"doc\":\"Nazev uctu (dlouha varianta) v primarnim systemu (SB, S" +
				"PZ, ...). Muze mit delku az 60 znaku.\",\"default\":null,\"type\":[\"null\",\"string\"]}," +
				"{\"name\":\"bic\",\"type\":\"string\"},{\"name\":\"iban\",\"type\":\"string\"},{\"name\":\"notice\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]}]}]}]}},{\"name\":\"paymentReceiver\",\"type\"" +
				":{\"type\":\"record\",\"name\":\"PaymentReceiver\",\"namespace\":\"cz.csas.avroschemas.admi" +
				"nisteredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"idCard\",\"default\":null" +
				",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"IdCard\",\"namespace\":\"cz.csas.avroschema" +
				"s.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"cardNumber\",\"doc" +
				"\":\"cislo dokladu\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"cardType\",\"d" +
				"oc\":\"typ ID dokladu (OP, cestovni pas, ridicsky prukaz...)\",\"default\":null,\"type" +
				"\":[\"null\",\"string\"]},{\"name\":\"issuer\",\"doc\":\"Udava kdo doklad vydal (urad).\",\"de" +
				"fault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"issuerCountry\",\"doc\":\"(doklad) vy" +
				"dal stat\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"validUntil\",\"default" +
				"\":null,\"type\":[\"null\",\"int\"]}]}]},{\"name\":\"liabilityPaymentRoleType\",\"type\":\"str" +
				"ing\"},{\"name\":\"permanentAddress\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\"," +
				"\"name\":\"PermanentAddress\",\"namespace\":\"cz.csas.avroschemas.administeredpayment_p" +
				"rocesspayment.v03_01\",\"fields\":[{\"name\":\"l1_recipient\",\"doc\":\"Adresni radek 1 Pr" +
				"ijmeni, Jmeno, Titul pred, Titul za\\r\\n\\r\\nPouziti formatovane adresy je popsano" +
				" primo v entite PostalAddress.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\"" +
				":\"l2_supplement\",\"doc\":\"Adresni radek 2, Doplnek\\r\\n\\r\\nPouziti formatovane adre" +
				"sy je popsano primo v entite PostalAddress.\",\"default\":null,\"type\":[\"null\",\"stri" +
				"ng\"]},{\"name\":\"l3_street\",\"doc\":\"Adresni radek 3, Ulice (nebo Cast obce, kdyz je" +
				" pole Ulice prazdne), „Cislo popisne/orientacni“ nebo „Cislo evidencni\\r\\n\\r\\nPo" +
				"uziti formatovane adresy je popsano primo v entite PostalAddress.\",\"default\":nul" +
				"l,\"type\":[\"null\",\"string\"]},{\"name\":\"l4_city\",\"doc\":\"Adresni radek 4, Obec/Cast " +
				"Obce\\r\\n\\r\\nPouziti formatovane adresy je popsano primo v entite PostalAddress.\"" +
				",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"l5_zipcode\",\"doc\":\"Adresni ra" +
				"dek 5, PSC, Posta\\r\\n\\r\\nPouziti formatovane adresy je popsano primo v entite Po" +
				"stalAddress.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"l6_country\",\"doc" +
				"\":\"Adresni radek 6, Stat. Pokud je to CR, pole se nevraci.\\r\\n\\r\\nPouziti format" +
				"ovane adresy je popsano primo v entite PostalAddress.\",\"default\":null,\"type\":[\"n" +
				"ull\",\"string\"]}]}]},{\"name\":\"person\",\"type\":{\"type\":\"record\",\"name\":\"Person\",\"na" +
				"mespace\":\"cz.csas.avroschemas.administeredpayment_processpayment.v03_01\",\"fields" +
				"\":[{\"name\":\"additionalDegree\",\"doc\":\"Additional academic degree. (Titul za jmene" +
				"m.)\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"birthCountry\",\"doc\":\"zeme" +
				" narozeni\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"birthPlace\",\"doc\":\"" +
				"misto (mesto) narozeni\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"citize" +
				"nships\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"" +
				"name\":\"Citizenship\",\"namespace\":\"cz.csas.avroschemas.administeredpayment_process" +
				"payment.v03_01\",\"fields\":[{\"name\":\"citizenship\",\"doc\":\"statni prislusnost / obca" +
				"nstvi\",\"type\":\"string\"}]}}]},{\"name\":\"degree\",\"doc\":\"Academic degree. (titul pre" +
				"d)\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"email\",\"doc\":\"emailova adr" +
				"esa\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"forename\",\"doc\":\"(krestni" +
				") jmeno\",\"type\":\"string\"},{\"name\":\"gender\",\"doc\":\"pohlavi\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"personalId\",\"doc\":\"Pro ceske obcany to je rodne cis" +
				"lo. Pro cizince cislo odvozene od datumu narozani (jak rc) a posledne 4 cislice " +
				"jsou devitky. Proto cizinci narozeni v jednom dni je maji rovnake.\",\"type\":\"stri" +
				"ng\"},{\"name\":\"surname\",\"doc\":\"prijmeni\",\"type\":\"string\"},{\"name\":\"taxResidency\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]}]}},{\"name\":\"verified\",\"type\":\"boolean\"}" +
				"]}},{\"name\":\"requestDate\",\"type\":\"long\"},{\"name\":\"requestId\",\"default\":null,\"typ" +
				"e\":[\"null\",\"string\"]},{\"name\":\"token\",\"default\":null,\"type\":[\"null\",\"string\"]},{" +
				"\"name\":\"userName\",\"default\":null,\"type\":[\"null\",\"string\"]}]}");
		private string _channel;
		private IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ExternalLiability> _externalLiabilityIds;
		/// <summary>
		/// identifikator pobocky (organizacni jednotky), napr. "001222_001_PRAHA 1,PC_PRAHA 1 (RYTIRSKA)", "CE7530_01_TYM VYVOJ A PODPORA INTERNICH APLIKACI", ...
		/// </summary>
		private string _orgUnitId;
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentInstruction _paymentInstruction;
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentReceiver _paymentReceiver;
		private long _requestDate;
		private string _requestId;
		private string _token;
		private string _userName;
		public virtual Schema Schema
		{
			get
			{
				return AdministeredPayment_processPayment._SCHEMA;
			}
		}
		public string channel
		{
			get
			{
				return this._channel;
			}
			set
			{
				this._channel = value;
			}
		}
		public IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ExternalLiability> externalLiabilityIds
		{
			get
			{
				return this._externalLiabilityIds;
			}
			set
			{
				this._externalLiabilityIds = value;
			}
		}
		/// <summary>
		/// identifikator pobocky (organizacni jednotky), napr. "001222_001_PRAHA 1,PC_PRAHA 1 (RYTIRSKA)", "CE7530_01_TYM VYVOJ A PODPORA INTERNICH APLIKACI", ...
		/// </summary>
		public string orgUnitId
		{
			get
			{
				return this._orgUnitId;
			}
			set
			{
				this._orgUnitId = value;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentInstruction paymentInstruction
		{
			get
			{
				return this._paymentInstruction;
			}
			set
			{
				this._paymentInstruction = value;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentReceiver paymentReceiver
		{
			get
			{
				return this._paymentReceiver;
			}
			set
			{
				this._paymentReceiver = value;
			}
		}
		public long requestDate
		{
			get
			{
				return this._requestDate;
			}
			set
			{
				this._requestDate = value;
			}
		}
		public string requestId
		{
			get
			{
				return this._requestId;
			}
			set
			{
				this._requestId = value;
			}
		}
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				this._token = value;
			}
		}
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.channel;
			case 1: return this.externalLiabilityIds;
			case 2: return this.orgUnitId;
			case 3: return this.paymentInstruction;
			case 4: return this.paymentReceiver;
			case 5: return this.requestDate;
			case 6: return this.requestId;
			case 7: return this.token;
			case 8: return this.userName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.channel = (System.String)fieldValue; break;
			case 1: this.externalLiabilityIds = (IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ExternalLiability>)fieldValue; break;
			case 2: this.orgUnitId = (System.String)fieldValue; break;
			case 3: this.paymentInstruction = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentInstruction)fieldValue; break;
			case 4: this.paymentReceiver = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentReceiver)fieldValue; break;
			case 5: this.requestDate = (System.Int64)fieldValue; break;
			case 6: this.requestId = (System.String)fieldValue; break;
			case 7: this.token = (System.String)fieldValue; break;
			case 8: this.userName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
