// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class PermanentAddress : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""PermanentAddress"",""namespace"":""cz.csas.avroschemas.administeredpayment_processpayment.v03_01"",""fields"":[{""name"":""l1_recipient"",""doc"":""Adresni radek 1 Prijmeni, Jmeno, Titul pred, Titul za\r\n\r\nPouziti formatovane adresy je popsano primo v entite PostalAddress."",""default"":null,""type"":[""null"",""string""]},{""name"":""l2_supplement"",""doc"":""Adresni radek 2, Doplnek\r\n\r\nPouziti formatovane adresy je popsano primo v entite PostalAddress."",""default"":null,""type"":[""null"",""string""]},{""name"":""l3_street"",""doc"":""Adresni radek 3, Ulice (nebo Cast obce, kdyz je pole Ulice prazdne), „Cislo popisne/orientacni“ nebo „Cislo evidencni\r\n\r\nPouziti formatovane adresy je popsano primo v entite PostalAddress."",""default"":null,""type"":[""null"",""string""]},{""name"":""l4_city"",""doc"":""Adresni radek 4, Obec/Cast Obce\r\n\r\nPouziti formatovane adresy je popsano primo v entite PostalAddress."",""default"":null,""type"":[""null"",""string""]},{""name"":""l5_zipcode"",""doc"":""Adresni radek 5, PSC, Posta\r\n\r\nPouziti formatovane adresy je popsano primo v entite PostalAddress."",""default"":null,""type"":[""null"",""string""]},{""name"":""l6_country"",""doc"":""Adresni radek 6, Stat. Pokud je to CR, pole se nevraci.\r\n\r\nPouziti formatovane adresy je popsano primo v entite PostalAddress."",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// Adresni radek 1 Prijmeni, Jmeno, Titul pred, Titul za
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		private string _l1_recipient;
		/// <summary>
		/// Adresni radek 2, Doplnek
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		private string _l2_supplement;
		/// <summary>
		/// Adresni radek 3, Ulice (nebo Cast obce, kdyz je pole Ulice prazdne), „Cislo popisne/orientacni“ nebo „Cislo evidencni
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		private string _l3_street;
		/// <summary>
		/// Adresni radek 4, Obec/Cast Obce
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		private string _l4_city;
		/// <summary>
		/// Adresni radek 5, PSC, Posta
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		private string _l5_zipcode;
		/// <summary>
		/// Adresni radek 6, Stat. Pokud je to CR, pole se nevraci.
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		private string _l6_country;
		public virtual Schema Schema
		{
			get
			{
				return PermanentAddress._SCHEMA;
			}
		}
		/// <summary>
		/// Adresni radek 1 Prijmeni, Jmeno, Titul pred, Titul za
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		public string l1_recipient
		{
			get
			{
				return this._l1_recipient;
			}
			set
			{
				this._l1_recipient = value;
			}
		}
		/// <summary>
		/// Adresni radek 2, Doplnek
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		public string l2_supplement
		{
			get
			{
				return this._l2_supplement;
			}
			set
			{
				this._l2_supplement = value;
			}
		}
		/// <summary>
		/// Adresni radek 3, Ulice (nebo Cast obce, kdyz je pole Ulice prazdne), „Cislo popisne/orientacni“ nebo „Cislo evidencni
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		public string l3_street
		{
			get
			{
				return this._l3_street;
			}
			set
			{
				this._l3_street = value;
			}
		}
		/// <summary>
		/// Adresni radek 4, Obec/Cast Obce
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		public string l4_city
		{
			get
			{
				return this._l4_city;
			}
			set
			{
				this._l4_city = value;
			}
		}
		/// <summary>
		/// Adresni radek 5, PSC, Posta
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		public string l5_zipcode
		{
			get
			{
				return this._l5_zipcode;
			}
			set
			{
				this._l5_zipcode = value;
			}
		}
		/// <summary>
		/// Adresni radek 6, Stat. Pokud je to CR, pole se nevraci.
		///
		///Pouziti formatovane adresy je popsano primo v entite PostalAddress.
		/// </summary>
		public string l6_country
		{
			get
			{
				return this._l6_country;
			}
			set
			{
				this._l6_country = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.l1_recipient;
			case 1: return this.l2_supplement;
			case 2: return this.l3_street;
			case 3: return this.l4_city;
			case 4: return this.l5_zipcode;
			case 5: return this.l6_country;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.l1_recipient = (System.String)fieldValue; break;
			case 1: this.l2_supplement = (System.String)fieldValue; break;
			case 2: this.l3_street = (System.String)fieldValue; break;
			case 3: this.l4_city = (System.String)fieldValue; break;
			case 4: this.l5_zipcode = (System.String)fieldValue; break;
			case 5: this.l6_country = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
