//// ------------------------------------------------------------------------------
//// <auto-generated>
////    Generated by avrogen, version 1.10.0.0
////    Changes to this file may cause incorrect behavior and will be lost if code
////    is regenerated
//// </auto-generated>
//// ------------------------------------------------------------------------------
//namespace cz.csas.avroschemas.abbyadministeredpayments.v03_01
//{
//	using System;
//	using System.Collections.Generic;
//	using System.Text;
//	using Avro;
//	using Avro.Specific;
	
//	public partial class Account : ISpecificRecord
//	{
//		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Account"",""namespace"":""cz.csas.avroschemas.abbyadministeredpayments.v03_01"",""fields"":[{""name"":""accountNumber"",""doc"":""Bank Account Number"",""default"":null,""type"":[""null"",""string""]},{""name"":""accountPrefix"",""doc"":""Bank Account Number Prefix"",""default"":null,""type"":[""null"",""string""]},{""name"":""bankCode"",""doc"":""Bank Code"",""default"":null,""type"":[""null"",""string""]},{""name"":""iban"",""default"":null,""type"":[""null"",""string""]}]}");
//		/// <summary>
//		/// Bank Account Number
//		/// </summary>
//		private string _accountNumber;
//		/// <summary>
//		/// Bank Account Number Prefix
//		/// </summary>
//		private string _accountPrefix;
//		/// <summary>
//		/// Bank Code
//		/// </summary>
//		private string _bankCode;
//		private string _iban;
//		public virtual Schema Schema
//		{
//			get
//			{
//				return Account._SCHEMA;
//			}
//		}
//		/// <summary>
//		/// Bank Account Number
//		/// </summary>
//		public string accountNumber
//		{
//			get
//			{
//				return this._accountNumber;
//			}
//			set
//			{
//				this._accountNumber = value;
//			}
//		}
//		/// <summary>
//		/// Bank Account Number Prefix
//		/// </summary>
//		public string accountPrefix
//		{
//			get
//			{
//				return this._accountPrefix;
//			}
//			set
//			{
//				this._accountPrefix = value;
//			}
//		}
//		/// <summary>
//		/// Bank Code
//		/// </summary>
//		public string bankCode
//		{
//			get
//			{
//				return this._bankCode;
//			}
//			set
//			{
//				this._bankCode = value;
//			}
//		}
//		public string iban
//		{
//			get
//			{
//				return this._iban;
//			}
//			set
//			{
//				this._iban = value;
//			}
//		}
//		public virtual object Get(int fieldPos)
//		{
//			switch (fieldPos)
//			{
//			case 0: return this.accountNumber;
//			case 1: return this.accountPrefix;
//			case 2: return this.bankCode;
//			case 3: return this.iban;
//			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
//			};
//		}
//		public virtual void Put(int fieldPos, object fieldValue)
//		{
//			switch (fieldPos)
//			{
//			case 0: this.accountNumber = (System.String)fieldValue; break;
//			case 1: this.accountPrefix = (System.String)fieldValue; break;
//			case 2: this.bankCode = (System.String)fieldValue; break;
//			case 3: this.iban = (System.String)fieldValue; break;
//			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
//			};
//		}
//	}
//}
