// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Citizenship : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Citizenship\",\"namespace\":\"cz.csas.avroschemas.administer" +
				"edpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"citizenship\",\"doc\":\"statni p" +
				"rislusnost / obcanstvi\",\"type\":\"string\"}]}");
		/// <summary>
		/// statni prislusnost / obcanstvi
		/// </summary>
		private string _citizenship;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Citizenship._SCHEMA;
			}
		}
		/// <summary>
		/// statni prislusnost / obcanstvi
		/// </summary>
		public string citizenship
		{
			get
			{
				return this._citizenship;
			}
			set
			{
				this._citizenship = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.citizenship;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.citizenship = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
