// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class PaymentInstruction : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""PaymentInstruction"",""namespace"":""cz.csas.avroschemas.administeredpayment_processpayment.v03_01"",""fields"":[{""name"":""domesticAccount"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""DomesticAccount"",""namespace"":""cz.csas.avroschemas.administeredpayment_processpayment.v03_01"",""fields"":[{""name"":""accountNumber"",""doc"":""Bank Account Number"",""type"":""string""},{""name"":""accountPrefix"",""doc"":""Bank Account Number Prefix"",""default"":null,""type"":[""null"",""string""]},{""name"":""bankCode"",""doc"":""Bank Code"",""type"":""string""}]}]},{""name"":""foreignAccount"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""ForeignAccount"",""namespace"":""cz.csas.avroschemas.administeredpayment_processpayment.v03_01"",""fields"":[{""name"":""accountName"",""doc"":""Nazev uctu (dlouha varianta) v primarnim systemu (SB, SPZ, ...). Muze mit delku az 60 znaku."",""default"":null,""type"":[""null"",""string""]},{""name"":""bic"",""type"":""string""},{""name"":""iban"",""type"":""string""},{""name"":""notice"",""default"":null,""type"":[""null"",""string""]}]}]}]}");
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.DomesticAccount _domesticAccount;
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ForeignAccount _foreignAccount;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PaymentInstruction._SCHEMA;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.DomesticAccount domesticAccount
		{
			get
			{
				return this._domesticAccount;
			}
			set
			{
				this._domesticAccount = value;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ForeignAccount foreignAccount
		{
			get
			{
				return this._foreignAccount;
			}
			set
			{
				this._foreignAccount = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.domesticAccount;
			case 1: return this.foreignAccount;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.domesticAccount = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.DomesticAccount)fieldValue; break;
			case 1: this.foreignAccount = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ForeignAccount)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
