// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class AdministeredPayment_processPayment : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"AdministeredPayment_processPayment\",\"namespace\":\"cz.csas" +
				".avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"chann" +
				"el\",\"type\":\"string\"},{\"name\":\"externalLiabilityIds\",\"type\":{\"type\":\"array\",\"item" +
				"s\":{\"type\":\"record\",\"name\":\"ExternalLiability\",\"namespace\":\"cz.csas.avroschemas." +
				"administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"externalLiabilityI" +
				"d\",\"doc\":\"Externi id zavazku\",\"type\":\"string\"}]}}},{\"name\":\"orgUnitId\",\"doc\":\"id" +
				"entifikator pobocky (organizacni jednotky)\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"paymentInstruction\",\"type\":{\"type\":\"record\",\"name\":\"PaymentInstruc" +
				"tion\",\"namespace\":\"cz.csas.avroschemas.administeredpayment_processpayment.v03_01" +
				"\",\"fields\":[{\"name\":\"domesticAccount\",\"default\":null,\"type\":[\"null\",{\"type\":\"rec" +
				"ord\",\"name\":\"DomesticAccount\",\"namespace\":\"cz.csas.avroschemas.administeredpayme" +
				"nt_processpayment.v03_01\",\"fields\":[{\"name\":\"accountNumber\",\"doc\":\"Bank Account " +
				"Number\",\"type\":\"string\"},{\"name\":\"accountPrefix\",\"doc\":\"Bank Account Number Pref" +
				"ix\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"bankCode\",\"doc\":\"Bank Code" +
				"\",\"type\":\"string\"}]}]},{\"name\":\"foreignAccount\",\"default\":null,\"type\":[\"null\",{\"" +
				"type\":\"record\",\"name\":\"ForeignAccount\",\"namespace\":\"cz.csas.avroschemas.administ" +
				"eredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"accountName\",\"doc\":\"Nazev " +
				"uctu (dlouha varianta) v primarnim systemu (SB, SPZ, ...). Muze mit delku az 60 " +
				"znaku.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"bic\",\"type\":\"string\"}," +
				"{\"name\":\"iban\",\"type\":\"string\"},{\"name\":\"notice\",\"default\":null,\"type\":[\"null\",\"" +
				"string\"]}]}]}]}},{\"name\":\"paymentReceiver\",\"default\":null,\"type\":[\"null\",{\"type\"" +
				":\"array\",\"items\":{\"type\":\"record\",\"name\":\"PaymentReceiver\",\"namespace\":\"cz.csas." +
				"avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"idCard" +
				"\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"IdCard\",\"namespace\":\"cz" +
				".csas.avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"" +
				"cardNumber\",\"doc\":\"cislo dokladu\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"nam" +
				"e\":\"cardType\",\"doc\":\"typ ID dokladu (OP, cestovni pas, ridicsky prukaz...)\",\"def" +
				"ault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"issuer\",\"doc\":\"Udava kdo doklad vy" +
				"dal (urad).\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"issuerCountry\",\"d" +
				"oc\":\"(doklad) vydal stat\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"vali" +
				"dUntil\",\"default\":null,\"type\":[\"null\",\"int\"]}]}]},{\"name\":\"liabilityPaymentRoleT" +
				"ype\",\"type\":\"string\"},{\"name\":\"permanentAddress\",\"default\":null,\"type\":[\"null\",{" +
				"\"type\":\"record\",\"name\":\"PermanentAddress\",\"namespace\":\"cz.csas.avroschemas.admin" +
				"isteredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"l1_recipient\",\"doc\":\"Ad" +
				"resni radek 1 Prijmeni, Jmeno, Titul pred, Titul za\\\\r\\\\n\\\\r\\\\nPouziti formatova" +
				"ne adresy je popsano primo v entite PostalAddress.\",\"default\":null,\"type\":[\"null" +
				"\",\"string\"]},{\"name\":\"l2_supplement\",\"doc\":\"Adresni radek 2, Doplnek\\\\r\\\\n\\\\r\\\\n" +
				"Pouziti formatovane adresy je popsano primo v entite PostalAddress.\",\"default\":n" +
				"ull,\"type\":[\"null\",\"string\"]},{\"name\":\"l3_street\",\"doc\":\"Adresni radek 3, Ulice " +
				"(nebo Cast obce, kdyz je pole Ulice prazdne), „Cislo popisne/orientacni“ nebo „C" +
				"islo evidencni\\\\r\\\\n\\\\r\\\\nPouziti formatovane adresy je popsano primo v entite P" +
				"ostalAddress.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"l4_city\",\"doc\":" +
				"\"Adresni radek 4, Obec/Cast Obce\\\\r\\\\n\\\\r\\\\nPouziti formatovane adresy je popsan" +
				"o primo v entite PostalAddress.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name" +
				"\":\"l5_zipcode\",\"doc\":\"Adresni radek 5, PSC, Posta\\\\r\\\\n\\\\r\\\\nPouziti formatovane" +
				" adresy je popsano primo v entite PostalAddress.\",\"default\":null,\"type\":[\"null\"," +
				"\"string\"]},{\"name\":\"l6_country\",\"doc\":\"Adresni radek 6, Stat. Pokud je to CR, po" +
				"le se nevraci.\\\\r\\\\n\\\\r\\\\nPouziti formatovane adresy je popsano primo v entite P" +
				"ostalAddress.\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"person\",\"ty" +
				"pe\":{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"cz.csas.avroschemas.administer" +
				"edpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"additionalDegree\",\"doc\":\"Add" +
				"itional academic degree. (Titul za jmenem.)\",\"default\":null,\"type\":[\"null\",\"stri" +
				"ng\"]},{\"name\":\"birthCountry\",\"doc\":\"zeme narozeni\",\"default\":null,\"type\":[\"null\"" +
				",\"string\"]},{\"name\":\"birthPlace\",\"doc\":\"misto (mesto) narozeni\",\"default\":null,\"" +
				"type\":[\"null\",\"string\"]},{\"name\":\"citizenships\",\"default\":null,\"type\":[\"null\",{\"" +
				"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Citizenship\",\"namespace\":\"cz.csas" +
				".avroschemas.administeredpayment_processpayment.v03_01\",\"fields\":[{\"name\":\"citiz" +
				"enship\",\"doc\":\"statni prislusnost / obcanstvi\",\"type\":\"string\"}]}}]},{\"name\":\"de" +
				"gree\",\"doc\":\"Academic degree. (titul pred)\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"email\",\"doc\":\"emailova adresa\",\"default\":null,\"type\":[\"null\",\"stri" +
				"ng\"]},{\"name\":\"forename\",\"doc\":\"(krestni) jmeno\",\"type\":\"string\"},{\"name\":\"gende" +
				"r\",\"doc\":\"pohlavi\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"personalId\"" +
				",\"doc\":\"Pro ceske obcany to je rodne cislo. Pro cizince cislo odvozene od datumu" +
				" narozani (jak rc) a posledne 4 cislice jsou devitky. Proto cizinci narozeni v j" +
				"ednom dni je maji rovnake.\",\"type\":\"string\"},{\"name\":\"surname\",\"doc\":\"prijmeni\"," +
				"\"type\":\"string\"},{\"name\":\"taxResidency\",\"default\":null,\"type\":[\"null\",\"string\"]}" +
				"]}},{\"name\":\"verified\",\"type\":\"boolean\"}]}}]},{\"name\":\"requestDate\",\"type\":\"long" +
				"\"},{\"name\":\"requestId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"token\"," +
				"\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"userName\",\"default\":null,\"type" +
				"\":[\"null\",\"string\"]}]}");
		private string _channel;
		private IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ExternalLiability> _externalLiabilityIds;
		/// <summary>
		/// identifikator pobocky (organizacni jednotky)
		/// </summary>
		private string _orgUnitId;
		private cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentInstruction _paymentInstruction;
		private IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentReceiver> _paymentReceiver;
		private long _requestDate;
		private string _requestId;
		private string _token;
		private string _userName;
		public virtual Schema Schema
		{
			get
			{
				return AdministeredPayment_processPayment._SCHEMA;
			}
		}
		public string channel
		{
			get
			{
				return this._channel;
			}
			set
			{
				this._channel = value;
			}
		}
		public IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ExternalLiability> externalLiabilityIds
		{
			get
			{
				return this._externalLiabilityIds;
			}
			set
			{
				this._externalLiabilityIds = value;
			}
		}
		/// <summary>
		/// identifikator pobocky (organizacni jednotky)
		/// </summary>
		public string orgUnitId
		{
			get
			{
				return this._orgUnitId;
			}
			set
			{
				this._orgUnitId = value;
			}
		}
		public cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentInstruction paymentInstruction
		{
			get
			{
				return this._paymentInstruction;
			}
			set
			{
				this._paymentInstruction = value;
			}
		}
		public IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentReceiver> paymentReceiver
		{
			get
			{
				return this._paymentReceiver;
			}
			set
			{
				this._paymentReceiver = value;
			}
		}
		public long requestDate
		{
			get
			{
				return this._requestDate;
			}
			set
			{
				this._requestDate = value;
			}
		}
		public string requestId
		{
			get
			{
				return this._requestId;
			}
			set
			{
				this._requestId = value;
			}
		}
		public string token
		{
			get
			{
				return this._token;
			}
			set
			{
				this._token = value;
			}
		}
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.channel;
			case 1: return this.externalLiabilityIds;
			case 2: return this.orgUnitId;
			case 3: return this.paymentInstruction;
			case 4: return this.paymentReceiver;
			case 5: return this.requestDate;
			case 6: return this.requestId;
			case 7: return this.token;
			case 8: return this.userName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.channel = (System.String)fieldValue; break;
			case 1: this.externalLiabilityIds = (IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.ExternalLiability>)fieldValue; break;
			case 2: this.orgUnitId = (System.String)fieldValue; break;
			case 3: this.paymentInstruction = (cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentInstruction)fieldValue; break;
			case 4: this.paymentReceiver = (IList<cz.csas.avroschemas.administeredpayment_processpayment.v03_01.PaymentReceiver>)fieldValue; break;
			case 5: this.requestDate = (System.Int64)fieldValue; break;
			case 6: this.requestId = (System.String)fieldValue; break;
			case 7: this.token = (System.String)fieldValue; break;
			case 8: this.userName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
