// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class DomesticAccount : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""DomesticAccount"",""namespace"":""cz.csas.avroschemas.administeredpayment_processpayment.v03_01"",""fields"":[{""name"":""accountNumber"",""doc"":""Bank Account Number"",""type"":""string""},{""name"":""accountPrefix"",""doc"":""Bank Account Number Prefix"",""default"":null,""type"":[""null"",""string""]},{""name"":""bankCode"",""doc"":""Bank Code"",""type"":""string""}]}");
		/// <summary>
		/// Bank Account Number
		/// </summary>
		private string _accountNumber;
		/// <summary>
		/// Bank Account Number Prefix
		/// </summary>
		private string _accountPrefix;
		/// <summary>
		/// Bank Code
		/// </summary>
		private string _bankCode;
		public virtual Schema Schema
		{
			get
			{
				return DomesticAccount._SCHEMA;
			}
		}
		/// <summary>
		/// Bank Account Number
		/// </summary>
		public string accountNumber
		{
			get
			{
				return this._accountNumber;
			}
			set
			{
				this._accountNumber = value;
			}
		}
		/// <summary>
		/// Bank Account Number Prefix
		/// </summary>
		public string accountPrefix
		{
			get
			{
				return this._accountPrefix;
			}
			set
			{
				this._accountPrefix = value;
			}
		}
		/// <summary>
		/// Bank Code
		/// </summary>
		public string bankCode
		{
			get
			{
				return this._bankCode;
			}
			set
			{
				this._bankCode = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.accountNumber;
			case 1: return this.accountPrefix;
			case 2: return this.bankCode;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.accountNumber = (System.String)fieldValue; break;
			case 1: this.accountPrefix = (System.String)fieldValue; break;
			case 2: this.bankCode = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
