// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class ForeignAccount : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""ForeignAccount"",""namespace"":""cz.csas.avroschemas.administeredpayment_processpayment.v03_01"",""fields"":[{""name"":""accountName"",""doc"":""Nazev uctu (dlouha varianta) v primarnim systemu (SB, SPZ, ...). Muze mit delku az 60 znaku."",""default"":null,""type"":[""null"",""string""]},{""name"":""bic"",""type"":""string""},{""name"":""iban"",""type"":""string""},{""name"":""notice"",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// Nazev uctu (dlouha varianta) v primarnim systemu (SB, SPZ, ...). Muze mit delku az 60 znaku.
		/// </summary>
		private string _accountName;
		private string _bic;
		private string _iban;
		private string _notice;
		public virtual Schema Schema
		{
			get
			{
				return ForeignAccount._SCHEMA;
			}
		}
		/// <summary>
		/// Nazev uctu (dlouha varianta) v primarnim systemu (SB, SPZ, ...). Muze mit delku az 60 znaku.
		/// </summary>
		public string accountName
		{
			get
			{
				return this._accountName;
			}
			set
			{
				this._accountName = value;
			}
		}
		public string bic
		{
			get
			{
				return this._bic;
			}
			set
			{
				this._bic = value;
			}
		}
		public string iban
		{
			get
			{
				return this._iban;
			}
			set
			{
				this._iban = value;
			}
		}
		public string notice
		{
			get
			{
				return this._notice;
			}
			set
			{
				this._notice = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.accountName;
			case 1: return this.bic;
			case 2: return this.iban;
			case 3: return this.notice;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.accountName = (System.String)fieldValue; break;
			case 1: this.bic = (System.String)fieldValue; break;
			case 2: this.iban = (System.String)fieldValue; break;
			case 3: this.notice = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
