// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace cz.csas.avroschemas.administeredpayment_processpayment.v03_01
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// SEPA datovy typ pro identifikaci zprav/transakci/a jine potreby
	/// </summary>
	public partial class String : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"String\",\"namespace\":\"cz.csas.avroschemas.administeredpay" +
				"ment_processpayment.v03_01\",\"fields\":[]}");
		public virtual Schema Schema
		{
			get
			{
				return String._SCHEMA;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
