// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace io.confluent.connect.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class ConnectDefault : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""ConnectDefault"",""namespace"":""io.confluent.connect.avro"",""fields"":[{""name"":""ID"",""type"":""long""},{""name"":""TARGET"",""type"":""string""},{""name"":""SOURCE"",""type"":""string""},{""name"":""ACCOUNT_CURRENCY"",""type"":""string""},{""name"":""ACCOUNT_PREFIX"",""type"":""string""},{""name"":""ACCOUNT_NUMBER"",""type"":""string""},{""name"":""ACCOUNT_DISPOSABLEBALANCE"",""default"":null,""type"":[""null"",""double""]},{""name"":""DISPOSABLEBALANCE_TIMESTAMP"",""default"":null,""type"":[""null"",{""type"":""long"",""logicalType"":""timestamp-millis"",""connect.version"":1,""connect.name"":""org.apache.kafka.connect.data.Timestamp""}]},{""name"":""RESULT"",""type"":""string""},{""name"":""CODE"",""type"":""string""},{""name"":""MESSAGE"",""type"":""string""},{""name"":""BUSINESSDAY"",""type"":""string""},{""name"":""PAYMENT_EXTERNALID"",""type"":""string""},{""name"":""TARGET_TIMESTAMP"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis"",""connect.version"":1,""connect.name"":""org.apache.kafka.connect.data.Timestamp""}}]}");
		private long _ID;
		private string _TARGET;
		private string _SOURCE;
		private string _ACCOUNT_CURRENCY;
		private string _ACCOUNT_PREFIX;
		private string _ACCOUNT_NUMBER;
		private System.Nullable<System.Double> _ACCOUNT_DISPOSABLEBALANCE;
		private System.Nullable<System.DateTime> _DISPOSABLEBALANCE_TIMESTAMP;
		private string _RESULT;
		private string _CODE;
		private string _MESSAGE;
		private string _BUSINESSDAY;
		private string _PAYMENT_EXTERNALID;
		private System.DateTime _TARGET_TIMESTAMP;
		public virtual Schema Schema
		{
			get
			{
				return ConnectDefault._SCHEMA;
			}
		}
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				this._ID = value;
			}
		}
		public string TARGET
		{
			get
			{
				return this._TARGET;
			}
			set
			{
				this._TARGET = value;
			}
		}
		public string SOURCE
		{
			get
			{
				return this._SOURCE;
			}
			set
			{
				this._SOURCE = value;
			}
		}
		public string ACCOUNT_CURRENCY
		{
			get
			{
				return this._ACCOUNT_CURRENCY;
			}
			set
			{
				this._ACCOUNT_CURRENCY = value;
			}
		}
		public string ACCOUNT_PREFIX
		{
			get
			{
				return this._ACCOUNT_PREFIX;
			}
			set
			{
				this._ACCOUNT_PREFIX = value;
			}
		}
		public string ACCOUNT_NUMBER
		{
			get
			{
				return this._ACCOUNT_NUMBER;
			}
			set
			{
				this._ACCOUNT_NUMBER = value;
			}
		}
		public System.Nullable<System.Double> ACCOUNT_DISPOSABLEBALANCE
		{
			get
			{
				return this._ACCOUNT_DISPOSABLEBALANCE;
			}
			set
			{
				this._ACCOUNT_DISPOSABLEBALANCE = value;
			}
		}
		public System.Nullable<System.DateTime> DISPOSABLEBALANCE_TIMESTAMP
		{
			get
			{
				return this._DISPOSABLEBALANCE_TIMESTAMP;
			}
			set
			{
				this._DISPOSABLEBALANCE_TIMESTAMP = value;
			}
		}
		public string RESULT
		{
			get
			{
				return this._RESULT;
			}
			set
			{
				this._RESULT = value;
			}
		}
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				this._CODE = value;
			}
		}
		public string MESSAGE
		{
			get
			{
				return this._MESSAGE;
			}
			set
			{
				this._MESSAGE = value;
			}
		}
		public string BUSINESSDAY
		{
			get
			{
				return this._BUSINESSDAY;
			}
			set
			{
				this._BUSINESSDAY = value;
			}
		}
		public string PAYMENT_EXTERNALID
		{
			get
			{
				return this._PAYMENT_EXTERNALID;
			}
			set
			{
				this._PAYMENT_EXTERNALID = value;
			}
		}
		public System.DateTime TARGET_TIMESTAMP
		{
			get
			{
				return this._TARGET_TIMESTAMP;
			}
			set
			{
				this._TARGET_TIMESTAMP = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ID;
			case 1: return this.TARGET;
			case 2: return this.SOURCE;
			case 3: return this.ACCOUNT_CURRENCY;
			case 4: return this.ACCOUNT_PREFIX;
			case 5: return this.ACCOUNT_NUMBER;
			case 6: return this.ACCOUNT_DISPOSABLEBALANCE;
			case 7: return this.DISPOSABLEBALANCE_TIMESTAMP;
			case 8: return this.RESULT;
			case 9: return this.CODE;
			case 10: return this.MESSAGE;
			case 11: return this.BUSINESSDAY;
			case 12: return this.PAYMENT_EXTERNALID;
			case 13: return this.TARGET_TIMESTAMP;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ID = (System.Int64)fieldValue; break;
			case 1: this.TARGET = (System.String)fieldValue; break;
			case 2: this.SOURCE = (System.String)fieldValue; break;
			case 3: this.ACCOUNT_CURRENCY = (System.String)fieldValue; break;
			case 4: this.ACCOUNT_PREFIX = (System.String)fieldValue; break;
			case 5: this.ACCOUNT_NUMBER = (System.String)fieldValue; break;
			case 6: this.ACCOUNT_DISPOSABLEBALANCE = (System.Nullable<System.Double>)fieldValue; break;
			case 7: this.DISPOSABLEBALANCE_TIMESTAMP = (System.Nullable<System.DateTime>)fieldValue; break;
			case 8: this.RESULT = (System.String)fieldValue; break;
			case 9: this.CODE = (System.String)fieldValue; break;
			case 10: this.MESSAGE = (System.String)fieldValue; break;
			case 11: this.BUSINESSDAY = (System.String)fieldValue; break;
			case 12: this.PAYMENT_EXTERNALID = (System.String)fieldValue; break;
			case 13: this.TARGET_TIMESTAMP = (System.DateTime)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
